![Creating emissions](co2-emissions.jpg)
  
When factoring heat generation required for the manufacturing and transportation of products, _Greenhouse gas emissions attributable to products, from food to sneakers to appliances, make up more than 75% of global emissions._ -[The Carbon Catalogue](https://www.nature.com/articles/s41597-022-01178-9)

Our data, which is publicly available on [here](https://springernature.figshare.com/articles/dataset/The_Carbon_Catalogue_public_database_Carbon_footprints_of_866_commercial_products_across_8_industry_sectors_and_5_continents/16908979), contains product carbon footprints (PCFs) for various companies. PCFs are the greenhouse gas emissions attributable to a given product, measured in CO<sub>2</sub> (carbon dioxide equivalent).

This data is stored in a PostgreSQL database containing one table, `prouduct_emissions`, which looks at PCFs by product as well as the stage of production that these emissions occurred. Here's a snapshot of what `product_emissions` contains in each column:

### `product_emissions`

| field                              | data type |
|------------------------------------|-----------|
| `id`                                 | `VARCHAR`   |
| `year`                               | `INT`       |
| `product_name`                       | `VARCHAR`   |
| `company`                            | `VARCHAR`   |
| `country`                            | `VARCHAR`   |
| `industry_group`                     | `VARCHAR`   |
| `weight_kg`                          | `NUMERIC`   |
| `carbon_footprint_pcf`               | `NUMERIC`   |
| `upstream_percent_total_pcf`         | `VARCHAR`   |
| `operations_percent_total_pcf`       | `VARCHAR`   |
| `downstream_percent_total_pcf`       | `VARCHAR`   |

In [1]:
--Number of unique companies
SELECT COUNT(DISTINCT company) AS num_unique_companies
FROM product_emissions;

   num_unique_companies
0                   145

In [2]:
--Total carbon footprint PCF of companies for all years
SELECT company, ROUND(SUM(carbon_footprint_pcf), 1) AS total_pcf
FROM product_emissions 
GROUP BY company
ORDER BY total_pcf DESC;

                                  company  total_pcf
0    Gamesa Corporación Tecnológica, S.A.  9778464.0
1                              Daimler AG  1594300.0
2                           Volkswagen AG   655960.0
3                       Hino Motors, Ltd.   191687.0
4                          Arcelor Mittal   167007.3
..                                    ...        ...
140               Times Microwave Systems        0.1
141                         CNX Resources        0.1
142                     Martin Bauer GmbH        0.0
143              Fabrica de Tapas Bavaria        0.0
144                                 Retal        0.0

[145 rows x 2 columns]

In [3]:
--Total carbon footprint PCF for each industry group for most recent year
SELECT industry_group, 
		COUNT(DISTINCT company) AS num_companies, 
		ROUND(SUM(carbon_footprint_pcf), 1) AS total_industry_footprint
FROM product_emissions 
WHERE year = (SELECT MAX(year) FROM product_emissions)
GROUP BY industry_group
ORDER BY total_industry_footprint DESC;

                       industry_group  num_companies  total_industry_footprint
0                           Materials              3                  107129.0
1                       Capital Goods              2                   94942.7
2     Technology Hardware & Equipment              4                   21865.1
3            Food, Beverage & Tobacco              1                    3161.5
4  Commercial & Professional Services              1                     740.6
5                 Software & Services              1                     690.0